name: Update Changelog

on:
  push:
    paths:
      - 'package.json'
    branches:
      - main # or your default branch name

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get version from package.json
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main

      - name: Update Changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          future-release: v${{ steps.package-version.outputs.current-version}}

      - name: Commit updated CHANGELOG.md
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG.md for version ${{ steps.package-version.outputs.current-version }}" || echo "No changes to commit"
          git push
